### ISSUE TITLE
Querying Firestore

### ISSUE THREAD

**Issue by bt-s** [bt-s/ipdw-project#36]
Once we can add books to the Firstore database in a principled manner, we will have to think of an effective way to query it.
We will need to do this in multiple places, e.g. in the searchbar in the navbar and in the filters on the /books page.

Firestore has good [documentation](https://firebase.google.com/docs/firestore/query-data/get-data), however, its functionality is more limited than SQL databases.
Therefore, we might want to look for an extension.

One option would be to use ElasticSearch with Firestore.
I have found two interesting articles on Medium that could be of help:
- https://medium.com/@acupajoe/wondering-how-to-get-elasticsearch-and-firebases-firestore-to-play-nice-1d84553aa280
- https://medium.com/joolsoftware/extending-firebase-with-cloud-functions-elasticsearch-129fbbb951e0

**Comment by Envl** [comment]
Sorry I never noticed that..hahah
